CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT NOT NULL CHECK (description <> ''),
    deliverydate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a web app', 1, 'Using JavaScript', '2019-05-12');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make an app', 1, 'Using Dart', '2019-05-13');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Desktop app', 3, 'Using C++', '2019-05-14');

INSERT INTO tasks (name, done, projectid)
VALUES ('Download VueJS', false, 1);

INSERT INTO tasks (name, done, projectid)
VALUES ('Create UI Web', false, 1);

INSERT INTO tasks (name, done, projectid)
VALUES ('Download Flutter', false, 2);


INSERT INTO tasks (name, done, projectid)
VALUES ('Design UI', false, 2);